#! /usr/bin/python3
from src.code.communication.comms import Serial_Comm
from src.code.communication.mqtt import MqttHelper
from enum import Enum
from src.code.control.motor import *
from src.code.control.pid import PID
import time

__DEBUG__ = True
__OUT_OF_RANGE_MESSAGE__ = 'OR'

class Arnold:
    # Arnold's to main sensory inputs
    ultra_data = None
    infra_data = None

    class Mode(Enum):
        FOLLOW = 1      # Default operation mode. Robot will blindly follow the carrot
        OBSTACLE = 2    # Activates on signal loss or path blockage. Robot switches to wall following
        WAIT = 3        # Halt actuation and wait for a usable

    def __init__(self, cs=200, dur=5000, maxsp = 1000):
        self.motors = ArnoldMotors({'frontLeft':'A','frontRight':'B','rearLeft':'C','rearRight':'D'}, cs)
        self.acting_mode = self.Mode.WAIT
        # Catch error for incorrect serial port


        self.ser = Serial_Comm()

        self.pid_tracking = PID(P=2.0, I=0.0, D=0.0)
        self.pid_avoidance = PID(P=5, I=0.0, D=0.0, SP = 0)

        self.constant_speed = cs
        self.left_speed = cs
        self.right_speed = cs
        self.duration = dur
        self.obstacle_position = -1 
        self.obstacle_distance = 0
        self.pid_output = 0.00

        self.max_speed = maxsp
        self.no_signal = 0xFFFFFFFF
        self.ultra_data_is_old = False

        self.mqttHelper = MqttHelper()

        try:
            self.mqttHelper.connect()
            self.mqttHelper.listen()
        except:
            if __DEBUG__:
                print('Could not connect to MQTT Helper')


    def live(self):
        'Main loop of Arnold. Updates model and perform motions'
        while True:
            try:
                if __DEBUG__:print('Started Read')
                new_data = self.ser.read_message()
                if __DEBUG__:print('Finished')

                if new_data[0] != None:
                    self.ultra_data = new_data[0]

                if new_data[1] != None:
                    self.infra_data = new_data[1]

                if __DEBUG__ :
                    if self.ultra_data != None: print('Ultrasonic: ', self.ultra_data)
                    if self.infra_data != None: print('Infrared: ', self.infra_data)

                #TODO: work out priority of mode and when to switch
                # If the data from the ultrasonics is old then switch modes
                if self.ultra_data != None and int(round(time.time() * 1000)) - self.ultra_data.timestamp > 1000:
                    self.mqttHelper.send_message(__OUT_OF_RANGE_MESSAGE__)
                    self.acting_mode = self.Mode.OBSTACLE
                    if __DEBUG__: print('Entering Obstacle Avoidance Mode')
                elif self.infra_data != None:
                    self.acting_mode = self.Mode.OBSTACLE
                elif self.ultra_data != None:
                    self.acting_mode = self.Mode.FOLLOW
                else:
                    self.acting_mode = self.Mode.WAIT

                # Update motion based on current data
                # if we have data for any of the modes, we can actuate on them
                if self.ultra_data != None or self.infra_data != None:
                    self.actuate()
                elif __DEBUG__:
                    print('No data received')

            except KeyboardInterrupt:
                self.motors.stop()
                print('Aborting Robot Operation')
                break


    def actuate(self):
        'Logic for selecting an actuation strategy and activating motors'
        if self.acting_mode == self.Mode.FOLLOW:
            # get the pid output to tune the speed and direction
            self.pid_output = self.pid_tracking.update_tracking(self.ultra_data.get_left(),
                                                       self.ultra_data.get_right(),
                                                       self.ultra_data.timestamp)
            #self.motors.set_turning_rate(-self.pid_output)

            dist = (self.ultra_data.get_left() + self.ultra_data.get_right()) / 2
            spd = 0
            if dist < 22500:
                spd = 0
            elif dist > 25000:
                spd = self.constant_speed
            else:
                spd = self.constant_speed * (dist - 22500) / 2500
            self.motors.set_parameters(spd, -self.pid_output)

        elif self.acting_mode == self.Mode.OBSTACLE:
            leftReading = self.infra_data.get_infrared_sensor_data(1)
            rightReading = self.infra_data.get_infrared_sensor_data(2)
            if leftReading != self.no_signal or rightReading != self.no_signal:
                #self.obstacle_distance = min(self.infra_data.get_infrared_sensor_data(0), self.infra_data.get_infrared_sensor_data(2))    
                #if self.obstacle_distance == self.infra_data.get_infrared_sensor_data(0):
                #    self.obstacle_position = 1
                #else:
                #    self.obstacle_position = 0
                leftDistance = min(leftReading, 80)
                rightDistance = min(rightReading, 80)
                if __DEBUG__:
                    print("Left distance is : {}".format(leftDistance))
                    print("Right distance is : {}".format(rightDistance))
                # turn to make the difference of the distances of each side equal to 0, i.e. stay inbetween both obstacles or go
                # straight if no obstacle in any side
                self.pid_output = self.pid_avoidance.update_collision_avoidance(leftDistance - rightDistance, self.infra_data.timestamp)

                self.motors.set_turning_rate(self.pid_output)

            # if there is no signal from both sides, turn to avoid the previously recorded corner
            #else:
            #    self.motors.turn(1000, self.obstacle_position*constant_speed, (1-self.obstacle_position)*constant_speed)  

        elif self.acting_mode == self.Mode.WAIT:
            if __DEBUG__:
                print('Wait Mode')

    def update_state(self):
        if self.ultra_data != None and int(round(time.time() * 1000)) - self.ultra_data.timestamp > 1000:
            # self.acting_mode = self.Mode.OBSTACLE
            if __DEBUG__:
                print('Entering Obstacle Avoidance Mode')
        else:
            self.acting_mode = self.Mode.FOLLOW

    def __del__(self):
        self.mqttHelper.stop_listening()

if __name__ == '__main__':
    arn = Arnold()
    arn.live()
